### ISSUE TITLE
"You are trying to sign in from a browser or app that doesn't allow us to keep your account secure."

### ISSUE THREAD

**Issue by mvcutter** [costastf/mapscookiegettercli#10]
Hi, I'm not sure if this is a change in google's auth process, but this message appears while trying to  use Chrome or Firefox. IE seems to login but an exception is thrown trying to parse the retrieved cookies.

I also could be doing something wrong as well! Please let me know if there is any additional information I can provide. I am attempting to use this for Home Assistant integration.
![LoginFail](https://user-images.githubusercontent.com/3201069/64025049-d0d0cd80-cb09-11e9-8fac-1073642466c6.png)

**Comment by costastf** [comment]
I am afraid that you are not doing anything wrong. Google just started blocking the usage of selenium. There are a few ways to try to mask the usage of selenium but that is another cat and mouse game that I am not interested in playing. I will as soon as possible edit the locationsharinglib project to be able to accept clear text cookies that can be retrieved by browser addons and that would hopefully make things easier. Until then, please be patient.

**Comment by costastf** [comment]
I have a branch on locationsharinglib that accepts text based cookies. If you don't mind giving that a try and reporting back it would be great so I can release it on Monday.

**Comment by mvcutter** [comment]
Absolutely I will try to test tonight or tomorrow. Thanks you so much!

**Comment by mvcutter** [comment]
Sorry I'm brain dead, how do I pull this in to the mapscookiegettercli project? I'm not easily seeing a reference to this library from there.

**Comment by costastf** [comment]
You don't :) the point is that this project is no longer needed since google has blocked it. But the point of this project was to get validated cookies to provide to locationsharinglib. I have refactored that to accept text based cookies that you can get from an add-on in chrome called cookies.txt . So install that on chrome, log in your maps account normally, export the cookies and provide them to locarionsharinglib and it should work. Makes sense?

**Comment by mvcutter** [comment]
Ok, think I'm closer... getting this as a failure now.

C:\Program Files\Python37\Scripts> python C:\Users\Mike\Desktop\something.py
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\locationsharinglib\locationsharinglib.py", line 82, in _validate_cookie
    cfile = open(cookies_file, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'cookies.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mike\Desktop\something.py", line 4, in <module>
    service = Service(cookies_file=cookies_file, authenticating_account=google_email)
  File "C:\Program Files\Python37\lib\site-packages\locationsharinglib\locationsharinglib.py", line 77, in __init__
    self._session = self._validate_cookie(cookies_file or '')
  File "C:\Program Files\Python37\lib\site-packages\locationsharinglib\locationsharinglib.py", line 89, in _validate_cookie
    raise InvalidCookies(message)
locationsharinglib.locationsharinglibexceptions.InvalidCookies: Could not open pickle file, either file does not exist or no read access.

**Comment by mvcutter** [comment]
Yeah I just realized it can't find the file... I'll mess with this more in the morning

**Comment by mvcutter** [comment]
One more try... found the file, but looks like there is a parsing error.

C:\>python something.py
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\locationsharinglib\locationsharinglib.py", line 83, in _validate_cookie
    session.cookies.update(pickle.load(cfile))
_pickle.UnpicklingError: unpickling stack underflow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "something.py", line 4, in <module>
    service = Service(cookies_file=cookies_file, authenticating_account=google_email)
  File "C:\Program Files\Python37\lib\site-packages\locationsharinglib\locationsharinglib.py", line 77, in __init__
    self._session = self._validate_cookie(cookies_file or '')
  File "C:\Program Files\Python37\lib\site-packages\locationsharinglib\locationsharinglib.py", line 86, in _validate_cookie
    raise InvalidCookies(message)
locationsharinglib.locationsharinglibexceptions.InvalidCookies: Could not load pickle file, probably invalid pickle.

**Comment by costastf** [comment]
You are not using the branch that can handle the text based cookies. Master is not up to date yet.

**Comment by costastf** [comment]
I have just merged into matter. Closing this as it is irrelevant with this project, if you have any issues please report on locationsharinglib issue tracker.
